package de.fastcrafter.castlewars;

public enum SelectingOrderTypes {
	PICKING_FLAG_RED,
	PICKING_FLAG_BLUE,
	REGISTERING_DISPENSER,
	REGISTERING_TOWER,
	REGISTERING_LOBBY_BLUE,
	REGISTERING_LOBBY_RED,
	PICKING_HIGHSCORES_A,
	PICKING_HIGHSCORES_B,
	PICKING_HIGHSCORES_C,
}
